select len(null)
select len('hello')
select len('')
select lower('Ayush')
select upper('Ayush')
select substring('Ayush', 1, 3)
select substring('AyushRudani',3,10)
select replace('abc123efg','123','xyz')
select replace('abcabcabc','c','5')
select ascii('a')
select ascii('A')
select ascii('z')
select ascii('Z')
select ascii('0')
select ascii('9')
select char(97)
select char(65)
select char(122)
select char(90)
select char(48)
select char(57)
select ltrim('   hello World')
select rtrim('hello World    ')
select substring('SQL server',1, 4)
select left('SQL server',4)
select right('SQL server',5)
select cast('1234.56' as varchar)
select CONVERT(int , 10.57)
select 'ayush'+space(10)+'a'
select 'ayush' + ' rudani'
SELECT CONCAT('ayush', ' rudani')
select reverse('Darshan')
select replicate('ayush ',3)
select STUFF('SQL Tutorial', 1, 3, 'HTML')
select isnumeric('ar')
select isnumeric('12')
select isnumeric(12)
select CHARINDEX('t','Customer')
